### PR TITLE
Allow to disable IVF, Flat index_key for large number of vectors (#68)

### PR DESCRIPTION
**Pull request by hitchhicker**

### CODE REVIEW

**Comment by rom1504** [comment]
I think we should do it in all cases, IE remove the option disable_ivf_flat_if_applicable
What do you think @victor-paltz ?

**Comment by hitchhicker** [comment]
I think that if people use GPU (`use_gpu`), even with ivf, flat, it is fast

**Comment by rom1504** [comment]
ok let's do if (nb embedding > 1M or use_gpu) { do ivf flat } else { don't }

**Comment by victor-paltz** [comment]
> I think we should do it in all cases, IE remove the option disable_ivf_flat_if_applicable What do you think @victor-paltz ?

We have now a lot of parameters in the main function, I think doing it all the time sounds reasonable.
But well, it can give additional insight to a high-level user when he reads the parameters so I am fine if we keep it like that

**Comment by hitchhicker** [comment]
I am conviced. Let's remove the option `disable_ivf_flat_if_applicable` and add the condition for gpu.
I will make a new commit.

**Comment by hitchhicker** [comment]
I will move the doc fix to another commit to keep this one clean.

**Pull request merged**
