### PR TITLE
load matrix in npz format  #89

### PR DESCRIPTION
**Pull request by futorio**
Solution for issue https://github.com/criteo/autofaiss/issues/89

### CODE REVIEW

**Comment by rom1504** [comment]
this needs:
* [ ] testing https://github.com/criteo/autofaiss/blob/master/tests/unit/test_embeddings_iterators.py#L96
* [ ] doc https://github.com/criteo/autofaiss#command-details

**Comment by rom1504** [comment]
Also this is not going to work with the lazy method
The implementation of the lazy numpy reader uses the fact that numpy on-disk format is predictable based on an item id.
That is not true when gzip is used.

so I think you need to use the eager method when using gzip.

**Comment by futorio** [comment]
> Also this is not going to work with the lazy method The implementation of the lazy numpy reader uses the fact that numpy on-disk format is predictable based on an item id. That is not true when gzip is used.
> 
> so I think you need to use the eager method when using gzip.

Hm, should i implement method get_lazy_array in class CompressedNumpyMatrixReader and pass NumpyEagerNdArray object?

**Comment by rom1504** [comment]
ahh I see your compression argument gets passed directly to fsspec compression support https://filesystem-spec.readthedocs.io/en/latest/features.html?highlight=compression#transparent-text-mode-and-compression

there's actually a chance that your current code would work if npz is compressing the whole npy file. I am not sure if this is the case though

**Comment by rom1504** [comment]
> The .npz format is the standard format for persisting multiple NumPy arrays on disk. A .npz file is a zip file containing multiple .npy files, one for each array.

https://numpy.org/devdocs/reference/generated/numpy.lib.format.html#npy-format 

no it's definitely not just the gzip of one npy file

so you're going to write a lot more code, passing the compression option to fsspec will not work

**Comment by futorio** [comment]
> > The .npz format is the standard format for persisting multiple NumPy arrays on disk. A .npz file is a zip file containing multiple .npy files, one for each array.
> 
> https://numpy.org/devdocs/reference/generated/numpy.lib.format.html#npy-format
> 
> no it's definitely not just the gzip of one npy file
> 
> so you're going to write a lot more code, passing the compression option to fsspec will not work

So yes it works with one file in npz archive. For more than 2 its choose the first np array

**Comment by futorio** [comment]
Oh, 

> 

Oh, maybe yes i should unzip matrix first, It's not worth it. Thanks for the library, i close pull request

**Pull request closed without merging**
